In [ ]:
aula2:modulo1

In [5]:
#criar sequencia python
python_list = [i for i in range(1_000_000 + 1)]

##tempo de execuçao: 0.107s
##memóris utilizada:39.8 mib

In [6]:

import numpy as np

In [7]:
#criar sequencia numpy
numpy_array = np.arange(0, 1_000_000 + 1, dtype='int64')
## Tempo de execução: 0.008 s
## Memória utilizada: 7.5 MIB

In [8]:
#calcular quadrados python

python_list_square = [i**2 for i in python_list]

##tempo de execução:0.520s
##Memoria utilizada: 38.4 MiB


In [9]:
#calcular quadrados numpy
numpy_array_square = numpy_array**2
##Tempo de execução:0.005s
##Memoria utilizada:7.5 MIB

## Tipo e acesso aos Elementos de um Array

In [10]:
#criando um Array
arr = np.array([1, 2, 3, 4, 5])
print(f"Elementos: {arr}, Tipo dos elementos: {arr.dtype}, Tamanho do array: {arr.shape}")

Elementos: [1 2 3 4 5], Tipo dos elementos: int64, Tamanho do array: (5,)


In [11]:
#acesso ao terceiro do array(indice 2):
Elementos = arr[2]
print(Elementos)


3


In [12]:
#obtendo elementos de indice 1 a 3
subset = arr[1:4]
print(subset)


[2 3 4]


In [13]:
#criando uma matriz
matrix  = np.arange(1., 10.).reshape((3, 3))
print(matrix)
print(f"Tipo dos elementos: {matrix.dtype}, Dimensões da matriz: {matrix.shape}")

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Tipo dos elementos: float64, Dimensões da matriz: (3, 3)


In [14]:
## acessando a 3 linha:
linha = matrix [2]
print(linha)


[7. 8. 9.]


In [15]:
## acessando a 2 coluna:
coluna = matrix[:, 1]
print(coluna)


[2. 5. 8.]


In [16]:
a = np.array([1.0, 2.0, 3.0])
b=2.0

Resultado = a * b
print(Resultado)


[2. 4. 6.]


## Multiplicação de Matrizes

In [17]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1], [2]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(B)

[[1]
 [2]]


In [19]:
## Multiplicaçao utilizando apenas listas python
C = [[0], [0], [0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(b)):
         C[i][j] += A[i][k] * B[k][j]
print(C)

TypeError: object of type 'float' has no len()

In [20]:
##agora vamos realizar a mesma operaçao com Numpy]
D = A @ B
print(D)

[[ 5]
 [11]
 [17]]


In [21]:
N = 500

A = np.arange(N*N, dtype='int64').reshape(N,N)
B = A * 2

C = A @ B
print(C)

##tempo de execuçao:0.196s
##Memoria utilizada: 5.8 MIb

[[   41541750000    41541999500    41542249000 ...    41665751500
     41666001000    41666250500]
 [  103916750000   103917499500   103918249000 ...   104289251500
    104290001000   104290750500]
 [  166291750000   166292999500   166294249000 ...   166912751500
    166914001000   166915250500]
 ...
 [31041916750000 31042165499500 31042414249000 ... 31165545251500
  31165794001000 31166042750500]
 [31104291750000 31104540999500 31104790249000 ... 31228168751500
  31228418001000 31228667250500]
 [31166666750000 31166916499500 31167166249000 ... 31290792251500
  31291042001000 31291291750500]]


In [3]:
A_lst = A.tolist()
B_lst = B.tolist()
C_lst = np.zeros_like(A).tolist()

for i in range(len(A_lst)):
    for k in range(len(B_lst)):
        C_lst[i][j] += A_lst[i][k] * B_lst [k][j]
print(C)
##Tempo de execuçao: 66.462s
##Memoria utilizada: 211.6 MiB

NameError: name 'A' is not defined